<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-12T01:40:41 TRT" name="Suite" finished-at="2024-03-12T01:41:38 TRT" duration-ms="56429">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:SelFrameworkDesign.tests.ErrorValidationsTest@71075444]" name="LoginErrorValidation" class="SelFrameworkDesign.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" name="submitOrder" class="SelFrameworkDesign.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-03-12T01:40:41 TRT" name="Sutmit Order Test" finished-at="2024-03-12T01:41:20 TRT" duration-ms="39202">
      <class name="SelFrameworkDesign.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:40:41 TRT" name="launchApplication" finished-at="2024-03-12T01:40:54 TRT" duration-ms="12333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:40:54 TRT" name="submitOrder" data-provider="getData" finished-at="2024-03-12T01:41:02 TRT" duration-ms="8706" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Fiko12345*, product=ZARA COAT 3, email=fiko@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:41:02 TRT" name="tearDown" finished-at="2024-03-12T01:41:02 TRT" duration-ms="113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:41:02 TRT" name="launchApplication" finished-at="2024-03-12T01:41:06 TRT" duration-ms="4026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:41:06 TRT" name="submitOrder" data-provider="getData" finished-at="2024-03-12T01:41:15 TRT" duration-ms="8190" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Csr12345-, product=ADIDAS ORIGINAL, email=csr@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:41:15 TRT" name="tearDown" finished-at="2024-03-12T01:41:15 TRT" duration-ms="156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:41:15 TRT" name="launchApplication" finished-at="2024-03-12T01:41:19 TRT" duration-ms="4201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:41:19 TRT" name="OrderHistoryTest" finished-at="2024-03-12T01:41:20 TRT" depends-on-methods="SelFrameworkDesign.tests.SubmitOrderTest.submitOrder" duration-ms="1280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameworkDesign.tests.SubmitOrderTest@19e4653c]" started-at="2024-03-12T01:41:20 TRT" name="tearDown" finished-at="2024-03-12T01:41:20 TRT" duration-ms="97" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SelFrameworkDesign.tests.SubmitOrderTest -->
    </test> <!-- Sutmit Order Test -->
    <test started-at="2024-03-12T01:41:21 TRT" name="Error Validation Test" finished-at="2024-03-12T01:41:38 TRT" duration-ms="16963">
      <class name="SelFrameworkDesign.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelFrameworkDesign.tests.ErrorValidationsTest@71075444]" started-at="2024-03-12T01:41:21 TRT" name="launchApplication" finished-at="2024-03-12T01:41:25 TRT" duration-ms="3946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:SelFrameworkDesign.tests.ErrorValidationsTest@71075444]" started-at="2024-03-12T01:41:25 TRT" name="LoginErrorValidation" finished-at="2024-03-12T01:41:25 TRT" duration-ms="696" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SelFrameworkDesign.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameworkDesign.tests.ErrorValidationsTest@71075444]" started-at="2024-03-12T01:41:26 TRT" name="tearDown" finished-at="2024-03-12T01:41:26 TRT" duration-ms="134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelFrameworkDesign.tests.ErrorValidationsTest@71075444]" started-at="2024-03-12T01:41:26 TRT" name="launchApplication" finished-at="2024-03-12T01:41:30 TRT" duration-ms="4516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:SelFrameworkDesign.tests.ErrorValidationsTest@71075444]" started-at="2024-03-12T01:41:30 TRT" name="ProductErrorValidation" finished-at="2024-03-12T01:41:37 TRT" duration-ms="6831" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at SelFrameworkDesign.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:42)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameworkDesign.tests.ErrorValidationsTest@71075444]" started-at="2024-03-12T01:41:37 TRT" name="tearDown" finished-at="2024-03-12T01:41:38 TRT" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SelFrameworkDesign.tests.ErrorValidationsTest -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
